### PR TITLE
Use cpu_count over sched_getaffinity

### LINKED ISSUE #109: os.sched_getaffinity is only available on Linux
Hi there,

The core initialisation line in `__innit__.py`
https://github.com/ratt-ru/shadeMS/blob/4026ff44e5831c3369905a80205e8b08035ccfbe/shade_ms/__init__.py#L6
breaks on non-linux systems. e.g. on macOS it produces
```
AttributeError: module 'os' has no attribute 'sched_getaffinity'
```
I'd recommend a simple change to use `os.cpu_count()` - I'll open a little PR to solve this issue.

### PR DESCRIPTION
**Pull request by AlecThomson**
Fixes #109

### CODE REVIEW

**Comment by AlecThomson** [comment]
Sorry for the delay @o-smirnov ! Now done

**Comment by o-smirnov** [comment]
Damn something failing in dask now -- I suspect we may need to pin a version. @sjperkins could you take a look please?

**Comment by o-smirnov** [comment]
Actually looks like this problem: https://github.com/ratt-ru/shadeMS/issues/111#issuecomment-1531593433

**Comment by Athanaseus** [comment]
Also, further dependency pinning and resolution are addressed here: #112

**Comment by Athanaseus** [comment]
@AlecThomson syncing this with master should resolve the failure.

**Comment by AlecThomson** [comment]
@Athanaseus I think that worked!

**Review by Athanaseus — APPROVED** [review]
LGTM!

**Pull request merged**
