### PR TITLE
Dataframe factory

### PR DESCRIPTION
**Pull request by sjperkins**
@o-smirnov Here's the dataframe factory. It broadcasts and ravels inputs (with possibly nan chunks) to create a dask Dataframe.

Used as follows:

```python
df = dataframe_factory(("row", "chan"),  x, ("row",),  y, ("chan",))
```

There's also some pytest test cases and I've updated setup.py to have a 'testing' extras that installs pytest. I'm being opinionated but it's really the best testing framework I've come across.

### CODE REVIEW

**Comment by sjperkins** [comment]
I got some llvmlite travis errors which I guess are related to https://github.com/ratt-ru/shadeMS/issues/43.

This is based on master branch but it's modular enough that I can rebase on any branch you suggest (antsy?).

This is probably also useful to ragavi (/cc @mulan-94) so would consider transitioning it into codex-africanus once it's been battle-tested.

**Comment by sjperkins** [comment]
Rebased this ontop of the auto-bounds branch

**Comment by sjperkins** [comment]
Test cases in a better state, but falls over on something datashader related. Perhaps the custom datashader fork?

```bash
Step 8/9 : RUN python3 -c 'import shade_ms.main'

 ---> Running in fccd12b4aaee

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/code/shade_ms/main.py", line 25, in <module>
    from . import data_plots, data_mappers
  File "/code/shade_ms/data_plots.py", line 244, in <module>
    class extract_multi(datashader.reductions.category_values):
AttributeError: module 'datashader.reductions' has no attribute 'category_values'

The command '/bin/sh -c python3 -c 'import shade_ms.main'' returned a non-zero code: 1

The command "docker build . -f .travis/${TARGET}.docker" exited with 1.
```

**Comment by o-smirnov** [comment]
Awesome, thanks for taking the effort to set up test cases @sjperkins. Yes it's mean to be run against my datashader fork for now. There's some code churn going on around these very classes right now (see my issues on the DS repo), so we just have to muddle along for a bit.

**Comment by sjperkins** [comment]
Test cases now run through: https://travis-ci.com/github/sjperkins/shadeMS/jobs/324158416

I've added a travis webhook. Hopefully new commits will give us the green circle/red cross icons that link directly to the test run.

**Comment by sjperkins** [comment]
> Right, so for now this is all tests and test cases. The dataframe factory is not yet invoked by the plotter code, but it sits there ready for use and the test cases illustrate how to use it. Correct @sjperkins?

Yes!

**Comment by o-smirnov** [comment]
@sjperkins I have added support for this, and indeed it has simplified the dataframe accumulation code most pleasingly. I had to make my own factory function to support >2 columns, but that was straightforward enough.  However, subsequent code bombs out with a ``KeyError`` on one of the column names. Which is weird, because in the debugger the dataframe looks perfectly fine to me and has the right columns.

Could you please take a look. The following will fail:
```
shadems any.ms -x FREQ -y amp
```

Use my datashader master, and the ``df-factory`` branch of shadeMS.

**Pull request merged**
