### PR TITLE
Support multicolumn in original dataframe_factory

### PR DESCRIPTION
**Pull request by sjperkins**
@o-smirnov I think this does what you want, although differently from the approach you were taking. I've gone with ``*arginds`` which implies an argument list of ``arg1, index1, arg2, index2, ... argn, indexn`` in the semantics of [dask.array.blockwise](https://docs.dask.org/en/latest/array-api.html#dask.array.core.blockwise).

Apologies if I've taken away a learning experience but I thought it better to move the code back towards an established blockwise pattern.

### CODE REVIEW

**Comment by sjperkins** [comment]
> Happy to go with whatever pattern you prefer in the interface, but it wasn't the pattern itself that was causing the problem?

No I don't think so. ``_create_dataframe`` was implictly expecting two arrays which it assigned to the (hardcoded) x and y columns of the DataFrame.  The actual column names matching those in the metadata must be supplied otherwise pandas throws a fit internally.

**Comment by sjperkins** [comment]
Also note that I've gone with `x` and `y` for the first two column names, followed by `c%d`. This is because datashader seemed to want the `x` and `y` data axes labelled explicitly. This might need to be changed to whatever datashader now considers appropriate.

**Comment by o-smirnov** [comment]
Does it? I just pass the axis names here and it seems to work fine:
```python
        raster = canvas.points(ddf, xaxis, yaxis, agg=datashader.by(category, agg_by))
```
Anyway, no errors now, but the numbers are coming up rubbish (in a very strange way -- they're off by 3 orders of magnitude, but not random). Could you please check if you get the same if you get the chance? Just do a basic ``-x real -y imag`` plot on any MS, and compare the output of ``df-factory`` vs ``test-ds-by-reduction``.

I've run out of steam for tonight but will dig in more tomorrow.

**Comment by sjperkins** [comment]
I get the following. supernovashell scale is different, but AF0236 looks the same.

| df-factory | test-ds-by-reduction |
|---|---|
| AF0236-df-factory | AF0236-test-ds-by-reduction |
| supernovashell-df-factory | supernovashell-test-ds-by-reduction |

**Comment by sjperkins** [comment]
Solved further by https://github.com/ratt-ru/shadeMS/pull/59#issuecomment-637393186

**Pull request merged**
